package mcir

import tbcommon "github.com/cloud-barista/cb-webtool/src/model/tumblebug/common"

type TbDataDiskInfo struct {
	AssociatedObjectList           []string `json:"associatedObjectList"`
	ConnectionName           string `json:"connectionName"`
	CreatedTime           string `json:"createdTime"`
	CspDataDiskId           string `json:"cspDataDiskId"`
	CspDataDiskName           string `json:"cspDataDiskName"`
	Description           string `json:"description"`
	DiskSize           string `json:"diskSize"`
	DiskType           string `json:"diskType"`

	ID           string `json:"id"`
	isAutoGenerated           bool `json:"isAutoGenerated"`
	KeyValueList []tbcommon.TbKeyValue `json:"keyValueList"`
	Name           string `json:"name"`
	Status           string `json:"status"`
	SystemLabel           string `json:"systemLabel"`

}
