package mcir

type TbSpecInfo struct {
	AssociatedObjectList []string `json:"associatedObjectList"`

	ConnectionName string  `json:"connectionName"`
	CostPerHour    float32 `json:"costPerHour"`
	CspSpecName    string  `json:"cspSpecName"`
	Description    string  `json:"description"`
	EbsBwMbps      int     `json:"ebsBwMbps"`

	EvaluationScore01 float32 `json:"evaluationScore_01"`
	EvaluationScore02 float32 `json:"evaluationScore_02"`
	EvaluationScore03 float32 `json:"evaluationScore_03"`
	EvaluationScore04 float32 `json:"evaluationScore_04"`
	EvaluationScore05 float32 `json:"evaluationScore_05"`
	EvaluationScore06 float32 `json:"evaluationScore_06"`
	EvaluationScore07 float32 `json:"evaluationScore_07"`
	EvaluationScore08 float32 `json:"evaluationScore_08"`
	EvaluationScore09 float32 `json:"evaluationScore_09"`
	EvaluationScore10 float32 `json:"evaluationScore_10"`
	EvaluationStatus  string  `json:"evaluationStatus"`

	GpumemGiB          int    `json:"gpumem_GiB"`
	GpuModel           string `json:"gpu_model"`
	GpuP2p             string `json:"gpu_p2p"`
	ID                 string `json:"id"`
	IsAutoGenerated    bool   `json:"isAutoGenerated"`
	MaxNumStorage      int    `json:"max_num_storage"`
	MaxTotalStorageTiB int    `json:"max_total_storage_TiB"`
	MemGiB             int    `json:"mem_GiB"`
	Name               string `json:"name"`
	Namespace          string `json:"namespace"`

	NetBwGbps             int    `json:"net_bw_Gbps"`
	NumCore               int    `json:"num_core"`
	NumGpu                int    `json:"num_gpu"`
	NumStorage            int    `json:"num_storage"`
	NumVCPU               int    `json:"numvCPU"`
	OrderInFilteredResult int    `json:"orderInFilteredResult"`
	OsType                string `json:"os_type"`
	StorageGiB            int    `json:"storage_GiB"`
}

type TbSpecInfos []TbSpecInfo
