package mcis

import (
	tbcommon "github.com/cloud-barista/cb-webtool/src/model/tumblebug/common"
)

type TbNLBInfo struct {
	AssociatedObjectList []string `json:"associatedObjectList"`
	ConnectionName       string   `json:"connectionName"`
	CreatedTime          string   `json:"createdTime"`
	CspNlbId             string   `json:"cspNlbId"`
	CspNlbName           string   `json:"cspNlbName"`
	Description          string   `json:"description"`

	HealthChecker TbNLBHealthCheckerInfo `json:"healthChecker"`
	Listener      TbNLBListenerInfo      `json:"listener"`
	Location      tbcommon.TbGeoLocation `json:"location"`
	TargetGroup   TbNLBTargetGroup       `json:"targetGroup"`

	ID              string                `json:"id"`
	IsAutoGenerated bool                  `json:"isAutoGenerated"`
	KeyValueList    []tbcommon.TbKeyValue `json:"keyValueList"`
	Name            string                `json:"name"`
	Status          string                `json:"status"`
	SystemLabel     string                `json:"systemLabel"`

	Scope string `json:"scope"`
	Type  string `json:"type"`

	McisID string `json:"mcisId"` // TB에서 해당항목이 없지만 NLB는 McisID가 필수라 추가함.
}
