package mcis

import tbcommon "github.com/cloud-barista/cb-webtool/src/model/tumblebug/common"

type TbNLBReq struct {
	ConnectionName string `json:"connectionName"`
	CspNlbId       string `json:"cspNlbId"`
	Description    string `json:"description"`
	Name           string `json:"name"`
	Scope          string `json:"scope"`
	Type           string `json:"type"`

	VNetId string `json:"vNetId"`

	HealthCheckerReq TbNLBHealthCheckerReq `json:"healthCheckerReq"`
	Listener         TbNLBListenerInfo     `json:"listener"`
	TargetGroup      TbNLBTargetGroup      `json:"targetGroup"`

	IsAutoGenerated bool                  `json:"isAutoGenerated"`
	KeyValueList    []tbcommon.TbKeyValue `json:"keyValueList"`
	Status          string                `json:"status"`
	SystemLabel     string                `json:"systemLabel"`
}
